version: '3.8'
services:
  postgres:
    container_name: cursos_postgres
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cursos